#pragma once
#define WIN32_NO_STATUS
#include <Windows.h>
struct IStreamVtbl; typedef struct IStreamVtbl IStreamVtbl;

typedef struct _RTL_MEMORY_STREAM_DATA {
#define RTLP_MEMORY_STREAM_DATA_PREFIX       \
    LONG                     ReferenceCount; \
    ULONG                    Flags;          \
    PUCHAR                   Current;        \
    PUCHAR                   Begin;          \
    PUCHAR                   End

	RTLP_MEMORY_STREAM_DATA_PREFIX;
	VOID(STDMETHODCALLTYPE* FinalRelease)(struct _RTL_MEMORY_STREAM_WITH_VTABLE*);
	IMalloc* ReservedForMalloc;
} RTL_MEMORY_STREAM_DATA, * PRTL_MEMORY_STREAM_DATA;

typedef struct _RTL_MEMORY_STREAM_WITH_VTABLE {
	const IStreamVtbl* StreamVTable;
	RTL_MEMORY_STREAM_DATA   Data;
} RTL_MEMORY_STREAM_WITH_VTABLE, * PRTL_MEMORY_STREAM_WITH_VTABLE;

typedef struct _BASE_SRV_MEMORY_MAPPED_STREAM_WITH_VTABLE {
	RTL_MEMORY_STREAM_WITH_VTABLE MemStream;
	HANDLE                        FileHandle;
} BASE_SRV_MEMORY_MAPPED_STREAM_WITH_VTABLE, * PBASE_SRV_MEMORY_MAPPED_STREAM_WITH_VTABLE;

typedef struct _RTL_OUT_OF_PROCESS_MEMORY_STREAM_DATA {
	RTLP_MEMORY_STREAM_DATA_PREFIX;
	VOID(STDMETHODCALLTYPE* FinalRelease)(struct _RTL_OUT_OF_PROCESS_MEMORY_STREAM_WITH_VTABLE*);
	HANDLE                    Process;
} RTL_OUT_OF_PROCESS_MEMORY_STREAM_DATA, * PRTL_OUT_OF_PROCESS_MEMORY_STREAM_DATA;

typedef struct _RTL_OUT_OF_PROCESS_MEMORY_STREAM_WITH_VTABLE {
	const IStreamVtbl* StreamVTable;
	RTL_OUT_OF_PROCESS_MEMORY_STREAM_DATA   Data;
} RTL_OUT_OF_PROCESS_MEMORY_STREAM_WITH_VTABLE, * PRTL_OUT_OF_PROCESS_MEMORY_STREAM_WITH_VTABLE;

typedef union _BASE_SRV_SXS_STREAM_UNION_WITH_VTABLE {
	BASE_SRV_MEMORY_MAPPED_STREAM_WITH_VTABLE Mmap;
	RTL_OUT_OF_PROCESS_MEMORY_STREAM_WITH_VTABLE  OutOfProcess;
} BASE_SRV_SXS_STREAM_UNION_WITH_VTABLE, * PBASE_SRV_SXS_STREAM_UNION_WITH_VTABLE;